/** @format */

import {
  CiAlignBottom,
  CiBank,
  CiCircleList,
  CiCoinInsert,
  CiImport,
  CiMoneyBill,
  CiShuffle,
  CiTimer,
  CiUser,
  CiViewBoard,
} from "react-icons/ci";
import {
  HiOutlineBan,
  HiOutlineBookOpen,
  HiOutlineChartPie,
  HiOutlineChartSquareBar,
  HiOutlineChatAlt,
  HiOutlineCode,
  HiOutlineColorSwatch,
  HiOutlineCurrencyDollar,
  HiOutlineDesktopComputer,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineHand,
  HiOutlineKey,
  HiOutlineLockClosed,
  HiOutlinePaperAirplane,
  HiOutlineShare,
  HiOutlineShieldCheck,
  HiOutlineTemplate,
  HiOutlineTrendingUp,
  HiOutlineUserAdd,
  HiOutlineUserGroup,
  HiOutlineVariable,
  HiOutlineViewGridAdd,
  HiUserCircle,
} from "react-icons/hi";

import { FaBed, FaPlane, FaCar , FaTaxi} from "react-icons/fa";

export type NavigationIcons = Record<string, JSX.Element>;

const navigationIcon: NavigationIcons = {
  report: <CiViewBoard />,
  users: <CiUser />,
  marketing: <CiCoinInsert />,
  transaction: <CiAlignBottom />,
  fileLoader: <CiImport />,
  account: <CiBank />,
  master: <CiCircleList />,
  mixing: <CiShuffle />,
  pricing: <CiMoneyBill />,
  apps: <HiOutlineViewGridAdd />,
  project: <HiOutlineChartSquareBar />,
  crm: <HiOutlineUserGroup />,
  sales: <HiOutlineTrendingUp />,
  crypto: <HiOutlineCurrencyDollar />,
  knowledgeBase: <HiOutlineBookOpen />,
  // account: <HiOutlineUserCircle />,
  user: <HiUserCircle />,
  uiComponents: <HiOutlineTemplate />,
  common: <HiOutlineColorSwatch />,
  feedback: <HiOutlineChatAlt />,
  dataDisplay: <HiOutlineDesktopComputer />,
  forms: <HiOutlineDocumentText />,
  navigation: <HiOutlinePaperAirplane />,
  graph: <HiOutlineChartPie />,
  authentication: <HiOutlineLockClosed />,
  signIn: <HiOutlineShieldCheck />,
  signUp: <HiOutlineUserAdd />,
  forgotPassword: <HiOutlineLockClosed />,
  resetPassword: <HiOutlineKey />,
  pages: <HiOutlineDocumentDuplicate />,
  welcome: <HiOutlineHand />,
  accessDenied: <HiOutlineBan />,
  guide: <HiOutlineBookOpen />,
  documentation: <HiOutlineDocumentText />,
  sharedComponentDoc: <HiOutlineShare />,
  utilsDoc: <HiOutlineVariable />,
  changeLog: <HiOutlineCode />,
  // report: <HiOutlineDocumentText />,
  dashboard: <CiTimer />,
  bed: <FaBed />,
  plane : <FaPlane/>,
  car : <FaCar/>,
  taxi : <FaTaxi/>,
};

export default navigationIcon;
